# Set theme
remote_theme: daviddarnes/alembic@main

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- Gemfile
- Gemfile.lock

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme


# 3. Gem settings
paginate: 5
paginate_path: dev/page:num

social:
  name: Serim Park
  links:
  - https://twitter.com/sparkinthebay
  - https://www.linkedin.com/in/serim-park-aa898741/
  - https://github.com/serimp



# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: USA/Los Angeles # Timezone for blog posts and alike



# 5. Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "assets/AdobeStock_257661067.jpeg"

# 6. Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages


# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en # Set the site language
url: 'https://serimp.github.io'
baseurl: ""
title: 'Daily log'
description: 'Daily log'
permalink: pretty
logo: "/assets/logos/shutterstock_1044115246.png"
repo: "https://github.com/serimp/"
email: "sparkinthebay@gmail.com"
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference



# 9. Site navigation
navigation_header:
- title: Home
  url: /
#- title: About
#  url: /about/
#- title: Dev
#  url: /dev/
#- title: Miscellaneous
#  url: /categories/
#- title: Search
#  url: /search/
# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

navigation_footer:
- title: Serim Park
  url: https://github.com/serimp


social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
    Twitter: https://twitter.com/sparkinthebay
    LinkedIn: https://www.linkedin.com/in/serim-park-aa898741/
    GitHub: https://github.com/serimp

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Thai+Looped
