# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme


# Pagination
paginate: 5
paginate_path: dev/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Dev
  url: /dev/
- title: Miscellaneous
  url: /categories/
- title: Search
  url: /search/
# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"


# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages




# Site settings
url: 'https://serimp.github.io'
baseurl: ''
title: 'Powered by Jekyll Alembic'
description: 'Where does the description goes '
permalink: pretty
logo: "images/shutterstock_1044115246.png"
repo: "https://github.com/serimp/"
email: "sparkinthebay@gmail.com"



social_links:
  Twitter: https://twitter.com/sparkinthebay
  LinkedIn: https://www.linkedin.com/in/serim-park-aa898741/
  GitHub: https://github.com/serimp
#  link: https://darn.es
  RSS: /feed.xml



sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Thai+Looped
